---
# kuttl version to use (must be specific version)
kuttl_version: 0.20.0

# Released version of the opm package (can be set to 'latest')
opm_version: latest

# operator-sdk version to use (must be specific version)
sdk_version: v1.41.1

# golang version
go_version: 1.24.6

# kustomize version to use (must be specific version)
kustomize_version: v5.0.3

# kubectl version to use (must be specific version)
kubectl_version: v1.25.7

# chainsaw version to use (must be specific version)
chainsaw_version: 0.2.12
